library(caret)
library(neuralnet)
df<-read.csv("RPractice2.csv")
df$Delay<-ifelse(df$Flight.Status=="delayed",1,0)
train.index<-sample(rownames(df),dim(df)[1]*0.6)
valid.index<-setdiff(rownames(df),train.index)
train.df<-df[train.index,]
valid.df<-df[valid.index,]
logit<-glm(Delay ~ CRS_DEP_TIME+DISTANCE+Weather+DAY_WEEK,data=train.df,family="binomial")
summary(logit)
pred_logit<-predict(logit,newdata=valid.df,type="response")
confusionMatrix(relevel(as.factor(ifelse(pred_logit>0.5,1,0)),ref="1"),relevel(as.factor(valid.df$Delay),ref="1"))
norm.values <- preProcess(df, method="range")
train.norm.df <- predict(norm.values, train.df)
valid.norm.df <- predict(norm.values, valid.df)
nn <- neuralnet(Delay ~ CRS_DEP_TIME+DISTANCE+Weather+DAY_WEEK, data = train.norm.df, linear.output=FALSE,hidden = 4)
plot(nn)
pred_nn <- compute(nn, valid.norm.df)
confusionMatrix(as.factor(ifelse(pred_nn$net.result>0.5, 1, 0)), as.factor(valid.df$Delay))
nn2 <- neuralnet(Delay ~ CRS_DEP_TIME+DISTANCE+Weather+DAY_WEEK, data = train.norm.df, linear.output=FALSE,hidden = c(2,2))
plot(nn2)
pred_nn2 <- compute(nn2, valid.norm.df)
confusionMatrix(as.factor(ifelse(pred_nn2$net.result>0.5, 1, 0)), as.factor(valid.df$Delay))
train.norm.df$Ontime<-1-train.norm.df$Delay
nn <- neuralnet(Delay + Ontime ~ CRS_DEP_TIME+DISTANCE+Weather+DAY_WEEK, data = train.norm.df, linear.output=FALSE,hidden = 4)
plot(nn)
pred_nn <- compute(nn, valid.norm.df)
predicted.class=ifelse(apply(pred_nn$net.result,1,which.max)==1,"1","0")
confusionMatrix(relevel(as.factor(predicted.class),ref="1"), 
                relevel(as.factor(valid.df$Delay),ref="1"))
nn2 <- neuralnet(Delay + Ontime ~ CRS_DEP_TIME+DISTANCE+Weather+DAY_WEEK, data = train.norm.df, linear.output=FALSE,hidden = c(2,2))
plot(nn2)
pred_nn2 <- compute(nn2, valid.norm.df)
predicted.class2=ifelse(apply(pred_nn2$net.result,1,which.max)==1,"1","0")
confusionMatrix(relevel(as.factor(predicted.class2),ref="1"), 
                relevel(as.factor(valid.df$Delay),ref="1"))
